In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# question 1
Yes there is a difference between the data types of the two variables.

In [6]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

# question 2

In [12]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# question 3

In [14]:
array_list = np.array(object = list_, dtype = int)

In [15]:
type(list_)

list

In [16]:
type(array_list)

numpy.ndarray

This means there is no difference in the data types of both variables

# question 4

In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

# question 5

In [24]:
import numpy.matlib as nm

In [25]:
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

# question 6

In [28]:
nm.eye(5,5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])